# Generated by Django 5.2.3 on 2025-07-03 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulk_mail', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emaillog',
            name='sender',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='emaillog',
            name='status',
            field=models.CharField(max_length=10),
        ),
    ]
